grid_search:
  module: sklearn.model_selection
  class: GridSearchCV
  params:
    cv: 5
    verbose: 2
    n_jobs : -1


model_selection:
  model_1:
    module: sklearn.ensemble
    class: RandomForestRegressor
    search_param_grid:
      criterion:
        - friedman_mse
      n_estimators :
        - 100

      max_depth:
        - 5
        - 6
        - 8
 
      max_features:
        - auto
  model_2:
    module: xgboost
    class: XGBRegressor
    search_param_grid:
      booster : 
        - gbtree
        - dart
      n_estimators :
        - 100
      learning_rate :
        - 0.1
        - 0.001
  model_3:
    module: catboost
    class: CatBoostRegressor
    search_param_grid:
      iterations:
        - 100
      learning_rate:
        - 0.1
        - 0.2
      depth:
        - 4
        - 5
      l2_leaf_reg:
        - 0.4
        - 0.5


 