grid_search:
  module: sklearn.model_selection
  class: GridSearchCV
  params:
    cv: 3
    verbose: 3
    n_jobs : -1


model_selection:
  model_1:
    module: sklearn.ensemble
    class: RandomForestRegressor
    search_param_grid:
      criterion:
        - squared_error
      n_estimators :
        - 100
        - 400
        - 700

      max_depth:
        - 5
        - 10
 
      max_features:
        - auto
        - sqrt

  model_2:
    module: xgboost
    class: XGBRegressor
    search_param_grid:
      booster : 
        - gbtree
        - gblinear
        - dart
      n_estimators :
        - 100
        - 200
        - 300
        - 400
      learning_rate :
        - 0.02
        - 0.1
        - 0.5
  model_3:
    module: catboost
    class: CatBoostRegressor
    search_param_grid:
      iterations:
        - 100
        - 200

      learning_rate:
        - 0.01
        - 0.02
        - 0.1
        - 0.04
    
      depth:
        - 3
        - 4
        - 5
      l2_leaf_reg:
        - 0.8
        - 0.9
