grid_search:
  module: sklearn.model_selection
  class: GridSearchCV
  params:
    cv: 3
    verbose: 3
    n_jobs : -1


model_selection:
  model_0:
    module: sklearn.tree
    class: DecisionTreeRegressor
    params:
      min_samples_leaf: 2
    search_param_grid:
      criterion:
        - squared_error
        - friedman_mse
        - absolute_error
        - poisson
      splitter:
        - best
        - random
      max_depth:
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
      max_features:
        - auto
        - sqrt
        - log2

  model_1:
    module: sklearn.ensemble
    class: RandomForestRegressor
    search_param_grid:
      criterion:
        - squared_error
        - absolute_error 
        - poisson
      n_estimators :
        - 100
        - 200
        - 300
        - 400
        - 500
        - 600
        - 700
        - 800
        - 900
      max_depth:
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
      max_features:
        - auto
        - sqrt
        - log2


      
  model_2:
    module: sklearn.linear_model
    class: LinearRegression
    search_param_grid:
      fit_intercept:
        - True
        - False
  
  model_3:
    module: xgboost
    class: XGBRegressor
    search_param_grid:
      base_score :
        - 0.5
        - 0.6
        - 0.7

      booster : 
        - gbtree
        - gblinear
        - dart
      n_estimators :
        - 100
        - 200
        - 300
        - 400
      learning_rate :
        - 0.1
        - 0.2
        - 0.3
        - 0.4
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
