
columns:
  Item_Fat_Content: object
  Item_Identifier: object
  Item_MRP: float64
  Item_Outlet_Sales: float64
  Item_Type: object
  Item_Visibility: float64
  Item_Weight: float64
  Outlet_Establishment_Year: int64
  Outlet_Identifier: object
  Outlet_Location_Type: object
  Outlet_Size: object
  Outlet_Type: object

selected_columns:
  - Item_Identifier
  - Item_Weight
  - Item_Fat_Content
  - Item_Visibility
  - Item_Type
  - Item_MRP
  - Outlet_Identifier
  - Outlet_Establishment_Year
  - Outlet_Size
  - Outlet_Type
  - Item_Outlet_Sales

categorical_columns:
  - Item_Identifier
  - Item_Fat_Content
  - Item_Type
  - Outlet_Identifier
  - Outlet_Size
  - Outlet_Type
  
numerical_columns:
- Item_Weight
- Item_Visibility
- Item_MRP
- Outlet_Establishment_Year

target_column: Item_Outlet_Sales
